* Fall 2022 - 127 - Work
* Name: Emily  Lin

* GitHub username: NotEmily3203

* Notes:
AUG.29.2022
- cd stands for change directory (ie cd intro)
- use python command in shell and write down file name to run file (ie python intro.py)
- version control allows you to commit changes to GitHub from Replit
- python, like many other languages, run program lines sequentially
SEP.1.2022
- turtle module has methods that let's you draw
- for loop is a way to iterate lines in python
SEP.12.2022
- refactoring variables can illeviate copy and pasting code to make it more versatile
SEP.19.2022
- github -> settings -> SSH keys -> make key, terminal -> ssh-keygen -> make note of file directory
SEP.22.2022
- always slowly test code components one at a time
- hash is an unique bit 16 hexadecimal number so you can identify changes
- HTML is a markup language because it does not solve any problems
SEP.29.2022
- you can import python modules and old modules. To import the random module, write import random at the top of the program. To import old modules, write import filename instead (without the .py)
OCT.3.2022
- lists can be indexed and spliced just like strings
- strings are immutable, once created you cannot change it. You can reassign variables. On the other hand, lists are mutable.
- when creating solutions, try to not permanently change the database, or document it if you do
OCT.17.2022
- mapping means going through each element in the list and transforming it. This is so prevalent in python that there is a generic method for it (nested functions). Basically, set a function as a parameter for a more general function.
OCT.20.2022
- list comprehension: python loops are so common that there's a shorthand for it. Basically if you want to turn something into a list, you can just put brackets around it.
- ex: [x*x for x in range(10)] x is the list name and the for loop will be in the list (it can be put into another function like random.randrange()). This whole thing can also be assigned to another variable.
NOV.7.2022
- the keys and values can be accessed and be put into a variable, becoming a psuedolist. It can be a list when you need it to be but you can't index it using brackets.
- tuples are immutable and are surrounded by parenthesis
- a,b,c = list can be a way to grab items in order, a and b and c are treated like an individual variable
- there's a thing called pretty printing so a dictionary looks better
NOV.14.2022
- stop words are words that aren't important

* Create folders and files as specified per assignment