* Fall 2022 - 127 - Work
* Name: Emily  Lin

* GitHub username: NotEmily3203

* Notes:
AUG.29.2022
- cd stands for change directory (ie cd intro)
- use python command in shell and write down file name to run file (ie python intro.py)
- version control allows you to commit changes to GitHub from Replit
- python, like many other languages, run program lines sequentially
SEP.1.2022
- turtle module has methods that let's you draw
- for loop is a way to iterate lines in python
SEP.12.2022
- refactoring variables can illeviate copy and pasting code to make it more versatile
SEP.19.2022
- github -> settings -> SSH keys -> make key, terminal -> ssh-keygen -> make note of file directory
SEP.22.2022
- always slowly test code components one at a time
- hash is an unique bit 16 hexadecimal number so you can identify changes
- HTML is a markup language because it does not solve any problems
SEP.29.2022
- you can import python modules and old modules. To import the random module, write import random at the top of the program. To import old modules, write import filename instead (without the .py)
OCT.3.2022
- lists can be indexed and spliced just like strings
- strings are immutable, once created you cannot change it. You can reassign variables. On the other hand, lists are mutable.
- when creating solutions, try to not permanently change the database, or document it if you do
OCT.17.2022
- mapping means going through each element in the list and transforming it. This is so prevalent in python that there is a generic method for it (nested functions). Basically, set a function as a parameter for a more general function.

* Create folders and files as specified per assignment
